### ISSUE TITLE
etree.parse Error

### ISSUE THREAD

**Issue by qCyb3r** [girishchandranc/autosarfactory#13]
Thank you foremost for providing the library.
After installing and trying to execute some code from the examples I ran into the following problem:

```
Traceback (most recent call last):
  File "c:\Users\user123\Desktop\AutosarFactory2\autosarfactory\autosarFactoryTest.py", line 22, in <module>
    root, status = autosarfactory.read(input_files)
  File "c:\Users\user123\Desktop\AutosarFactory2\autosarfactory\autosarfactory\autosarfactory.py", line 39, in read    
    tree = etree.parse(file, etree.XMLParser(remove_blank_text=True))
  File "src\lxml\etree.pyx", line 3521, in lxml.etree.parse
  File "src\lxml\parser.pxi", line 1859, in lxml.etree._parseDocument
  File "src\lxml\parser.pxi", line 1885, in lxml.etree._parseDocumentFromURL
  File "src\lxml\parser.pxi", line 1789, in lxml.etree._parseDocFromFile
  File "src\lxml\parser.pxi", line 1177, in lxml.etree._BaseParser._parseDocFromFile
  File "src\lxml\parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src\lxml\parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src\lxml\parser.pxi", line 652, in lxml.etree._raiseParseError
OSError: Error reading file 'c:\Users\user123\Desktop\AutosarFactory2\autosarfactory\resources\components.arxml': failed to load external entity "file:/c:/Users/user123/Desktop/AutosarFactory2/autosarfactory/resources/components.arxml"   
PS C:\Users\user123\Desktop\AutosarFactory2>
```

**Comment by AD1D1** [comment]
Hi girishchandranc,

I am too facing the exact error, when I run this:

files = ['interface.arxml', 'datatypes.arxml']
root, status = autosarfactory.read(files)

I get the following error:

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call
last)
Cell In[10], line 1
----> 1 root, status = autosarfactory.read(files)

File
c:\Users\users12345\Desktop\autosarfactory\autosarfactory\autosarfactory.py:42,
in read(files)
      40     status &= __read_folder(file)
      41 else:
---> 42     status &= __read_file(file)
      43 if status is False:
      44     break

File
c:\Users\users12345\Desktop\autosarfactory\autosarfactory\autosarfactory.py:67,
in __read_file(file)
      65 global __autosarNode__
      66 status = False
---> 67 tree = etree.parse(file,
etree.XMLParser(remove_blank_text=True))
      69 if tree is not None and tree.getroot() is not None:
      70     if etree.QName(tree.getroot()).localname == 'AUTOSAR':

File src\lxml\etree.pyx:3541, in lxml.etree.parse()

File src\lxml\parser.pxi:1879, in lxml.etree._parseDocument()

File src\lxml\parser.pxi:1905, in lxml.etree._parseDocumentFromURL()
...
File src\lxml\parser.pxi:728, in lxml.etree._handleParseResult()

File src\lxml\parser.pxi:655, in lxml.etree._raiseParseError()

OSError: Error reading file 'interface.arxml': failed to load external
entity "interface.arxml"

First I tried it out with components.arxml, thinking there was somefault with components.arxml, I tried it with interface.arxml it threw up the same thing then with interfance.arxml - same again:/

I'm just thinking this error is cause of a difference in schema maybe? do we need to define a schema in the code for the parsing to work?

Thanks :)

**Comment by girishchandranc** [comment]
Hi guys,

I am not sure if you are passing the file location properly? Maybe, the path is not properly escaped? 
@qCyb3r , Using single backlash in the file path may cause python to consider it as escape sequence. Could you check if using double backslash could help? Or better to use forward slashes in the path. Say changing the path to c:\\Users\\user123\\Desktop\\AutosarFactory2\\autosarfactory\\resources\\components.arxml or c:/Users/user123/Desktop/AutosarFactory2/autosarfactory/resources/components.arxml. 

@AD1D1 , it has not to do with schema. Here also, I reckon, its due to the issue with non.existence of file. I also get to see this error when the file location is not properly passed. Could you please make sure that the arxml files exist in the path from where the python script is run? If you still, want to keep it in the same folder as script, then could you add relative path from the python file to the arxml file, like we did it in the [test](https://github.com/girishchandranc/autosarfactory/tree/main/tests/test_autosarmodel.py)

Please let me know if it helps. 
Thanks!

**Comment by girishchandranc** [comment]
Hi @qCyb3r ,
Thanks for sharing the code snippet. Are you sure the file name is "interface**s**.arxml"? If you took it from "Examples/generated", then the file name is "interface.arxml". Noticed the additional "s" in the file name. 
I tried it by renaming the file and it seems to work for me. Can you please check again?

Thanks!

**Comment by qCyb3r** [comment]
Thanks a lot. I missed to see that "tests" is missing from the file path.
Editing this line solved the issue: `resourcesDir = os.path.join(os.path.dirname(__file__), '**tests\\**resources')`
